### ISSUE TITLE
Make virus checking async

### ISSUE THREAD

**Issue by icewind1991** [owncloud/files_antivirus#19]
Currently the anti virus check is sync, meaning that it delays writing and uploading.

Simply moving the check into an async job wont work since then an uploaded virus could be downloaded before the infected file is detected.
A way around that would be to have a storage wrapper that block read access to any file that hasn't been checked yet, that way a file could be uploaded by the sync client, renamed, shared to another user all without having to wait for the (potentially) slow virus scanner and without any risk of an infected file spreading

**Comment by MTRichards** [comment]
OOh! This is a cool idea for a-sync jobs of any kind on a file...It is there, but can't be seen.

As long as we throw an error such as "file is processing" or something so the UX is smooth, would this work for other jobs too, such as a DLP scan?
@karlitschek @DeepDiver1975

**Comment by karlitschek** [comment]
@icewind1991 This is an interesting idea. We have to assume that our clients and 3rdparty clients can handle such "blocked" requests in the right way. If this is only a matter of seconds than it might work. But if the external process takes several minutes than this might be a problem. Not sur if this is ok for all our async usecases.
But definitely and interesting direction.
@DeepDiver1975 what do you think?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 what do you think?

For sure interesting - this ticket was opened after @icewind1991 explained me his idea.

Best would be to have a POC which we can easly hook up against dav clients (cadaver and oc desktop) to see if this works out properly.

As a more general approach this might help in many areas where we want to have async operations.

@karlitschek if you agree I'd like @icewind1991 to implement a general purpose POC (not specific to antivirus) so that we can test this.

**Comment by karlitschek** [comment]
Good idea. Let´s do this and explorer how far this ideas carries.

**Comment by VicDeo** [comment]
Started https://github.com/owncloud/files_antivirus/pull/27
