### ISSUE TITLE
Antivirus 0.15.1

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/files_antivirus#307]
### Reason

- Release needed for #306 // #304 

### QA

- [x] Create **QA Milestone**
- [x] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [x] Create "$version Testplan" #308 @davitol 

### Documentation

- [ ] Changes in the docs needed?

### Marketing

- [ ] Ping @owncloud/marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build

All actions to be done on the release branch from here:
- [x] Bump version in info.xml (no version suffix)
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version' (final release date unknown)

#### Beta/RC

- [x] Create github tag for 'v${version}RC1' on release branch @patrickjahns 
- [x] Build and sign RC tarball from github tag 'v${version}RC1' (see
  handbook for how to build) @patrickjahns 
- [x] Upload as Github release using changelog entries @patrickjahns 
- [ ] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch @davitol  

#### Final

- [x] Create github tag for final 'v${version}' on release branch @patrickjahns 
- [x] Build and sign final tarball from github tag 'v${version}' (see
  handbook for how to build) @patrickjahns 
- [x] Upload as Github release using changelog entries @patrickjahns 
- [x] Smoke test tarball (at least install + enable) @patrickjahns 

### Publishing

- [x] Upload tarball to marketplace (see handbook for details) @patrickjahns 
- [x] Publish tarball for customers (see handbook for details) @patrickjahns 
- [x] Send mail to release-coordination with link to this ticket and to the changelog @patrickjahns 

### Post-release

- [x] Rename QA milestone to '$version' @patrickjahns 
- [ ] Add a new 'Unreleased' section in CHANGELOG.md and add release date '$version - $currentDate' (ex: 3.1.5 - 2018-08-01) @patrickjahns 
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number @patrickjahns

**Comment by individual-it** [comment]
@patrickjahns please build RC1 tarball

**Comment by patrickjahns** [comment]
RC1 tarball is available here https://github.com/owncloud/files_antivirus/releases/tag/v0.15.1RC1

**Comment by davitol** [comment]
Why do we want to release with ```min-version="10.2```?

Is there an strong reason for that? (cc @pmaier1 )

**Comment by patrickjahns** [comment]
@davitol 
This is related to the deprecation of php5.6 in the app - 10.2 also is no longer supporting php 5.6 ( afaik )

**Comment by davitol** [comment]
@patrickjahns Ok, I knew that 10.2 could be due to PHP 5.6 deprecation, but Antivirus 0.15.1 is a kind of quick fix of 0.15.0, that was available for previous versions too. So if someone has installed 0.15.0 in a 10.0/10.1 oC Server, he won't be able to get the hotfix. But as said, OK for me keep ```min-version="10.2"``` if deprecation of php5.6 is a stronger reason

**Comment by phil-davis** [comment]
Note: we put `min-version="10.2"` in `master` of each app, only really because we are only doing automated CI against a QA tarball that is `10.2` and later.

If we want, it is possible to back-up `min-version` to `10.1` or `10.0` in a release branch. We just need to do testing against whatever core `min-version` we choose (and verify that the app still has PHP 5.6 compatible code) That was done in the early days of `10.2` coming out.

**Comment by davitol** [comment]
@patrickjahns tarball is QA-ready
