### ISSUE TITLE
Shared file scanning: File does not exists

### ISSUE THREAD

**Issue by dbeniamine** [owncloud/files_antivirus#74]
Hello,

I use clam 0.98.7 in socket mode with ownclooud 8.1.1 and I have a weird issue:
Their is one file (file.pdf) in a shared directory (dir) from a user A to a user B that is constantly scanned in user B home by clam while it actually exists only in A's home directory ...

```
{"reqId":"e7ts7fzrU2CXIvdH8E9h","remoteAddr":"","app":"files_antivirus","message":"File does not exist. File: 2023 Path: B\/files\/dir\/file.pdf","level":3,"time":"2015-09-11T01:00:24+00:00"}
{"reqId":"e7ts7fzrU2CXIvdH8E9h","remoteAddr":"","app":"no app in context","message":"Error while running background job: ","level":3,"time":"2015-09-11T01:00:24+00:00"}
```

How can I tell owncloud /clam to stop trying to scan this file ?

P.S: I originally submit the bug here by error https://github.com/owncloud/apps/issues/2103 ...

**Comment by karlitschek** [comment]
@VicDeo any idea?

**Comment by VicDeo** [comment]
@dbeniamine you can put it's fileId into `oc_files_antivirus` table 
something like
`insert into files_antivirus (fileid, check_time) values (FILEID, TIMESTAMP);`
where FILEID is fileId of that file (2023 in your case)
and TIMESTAMP is current unixtime e.g. http://www.epochconverter.com/

**Comment by dbeniamine** [comment]
@VicDeo: thanks for your reply.

When I ran the sql line, it appears that the file was already in table with timestamp: `1442388629`
I guess an upgrade solved the problem ...

Still thanks for your help :)

**Comment by VicDeo** [comment]
@dbeniamine hm. I remember there was an issue with resolving path by fileId for shared directory content, but if I'm not mistaken it was fixed before 8.1 release.
So no such log entries any more?

**Comment by dbeniamine** [comment]
No nothing since october 1st (the day I purged the logs), so I guess it's okay for me (I have a lot of other files shared without problems).

**Comment by JochenHWezel** [comment]
![image](https://cloud.githubusercontent.com/assets/14078625/16022258/3cda18b4-31b7-11e6-880b-50466faecc2e.png)
Same to me: for some reasons (maybe I moved the owncloud data dir after immediately after first setup, but then it already created some files somewhere and can't find them any more) I also get this boring file not found message every few minutes in my log

Isn't it possible to detect that a file is not available in file system and to remove the scan job for it?

Or maybe the file record should better be removed from database completely, then it might be an issue of the core component instead of this file_antivirus plugin?!

**Comment by VicDeo** [comment]
should be fixed with https://github.com/owncloud/files_antivirus/pull/118
